/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksRouteImport } from './routes/books'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ReadBookChapterRouteImport } from './routes/read.$book.$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadBookChapterRoute = ReadBookChapterRouteImport.update({
  id: '/read/$book/$chapter',
  path: '/read/$book/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/read/$book/$chapter': typeof ReadBookChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/read/$book/$chapter': typeof ReadBookChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books': typeof BooksRoute
  '/login': typeof LoginRoute
  '/saved': typeof SavedRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/read/$book/$chapter': typeof ReadBookChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/books'
    | '/login'
    | '/saved'
    | '/profile'
    | '/search'
    | '/auth/callback'
    | '/api/auth/$'
    | '/read/$book/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/books'
    | '/login'
    | '/saved'
    | '/profile'
    | '/search'
    | '/auth/callback'
    | '/api/auth/$'
    | '/read/$book/$chapter'
  id:
    | '__root__'
    | '/'
    | '/books'
    | '/login'
    | '/saved'
    | '/profile'
    | '/search'
    | '/auth/callback'
    | '/api/auth/$'
    | '/read/$book/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksRoute: typeof BooksRoute
  LoginRoute: typeof LoginRoute
  SavedRoute: typeof SavedRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ReadBookChapterRoute: typeof ReadBookChapterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$book/$chapter': {
      id: '/read/$book/$chapter'
      path: '/read/$book/$chapter'
      fullPath: '/read/$book/$chapter'
      preLoaderRoute: typeof ReadBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksRoute: BooksRoute,
  LoginRoute: LoginRoute,
  SavedRoute: SavedRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ReadBookChapterRoute: ReadBookChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
